services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: "./api/.env"
    ports:
      - "4201:8080"
    volumes:
      - ./api/src:/api/src
      - ./api/package.json:/api/package.json
      - ./api/index.ts:/api/index.ts