services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: "./api/.env"
    ports:
      - "4201:8080"
    volumes:
      - ./api/src:/api/src
      - ./api/package.json:/api/package.json
      - ./api/index.ts:/api/index.ts
  web-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: "./app/.env"
    ports:
      - "3000:8080"
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
